# Generated by Django 3.0.8 on 2020-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20201204_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='starred',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
